apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: bastion
spec:
  ports:
  - name: proxy
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: proxy-tls
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: admin
    port: 8001
    protocol: TCP
    targetPort: 8001
  - name: admin-tls
    port: 8444
    protocol: TCP
    targetPort: 8444
  selector:
    pod-name: kong
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: bastion
  labels:
    app: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-name: kong
  template:
    metadata:
      labels:
        pod-name: kong
    spec:
      containers:
      - name: kong
        image: "docker.io/francois238/kongoidc:12.0"
        imagePullPolicy: IfNotPresent
        ports:
        - name: proxy
          protocol: TCP
          containerPort: 8000
        - name: proxy-tls
          protocol: TCP
          containerPort: 8443
        - name: admin
          protocol: TCP
          containerPort: 8001
        - name: admin-tls
          protocol: TCP
          containerPort: 8444
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_PROXY_LISTEN
          value: 0.0.0.0:8000, 0.0.0.0:8443 ssl
        - name: KONG_ADMIN_LISTEN
          value: 0.0.0.0:8001, 0.0.0.0:8444 ssl